addons:
  apt:
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
install:
    - npm install
script:
    - npm run ci
